# Generated by Django 4.1 on 2024-09-10 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0004_alter_pregunta_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Contraseña'),
        ),
    ]
