# Generated by Django 4.1 on 2024-09-11 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0005_usuario_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes'),
        ),
    ]
